###

POST http://localhost:8080/api/admin
Content-Type: application/json

{
    "id" : "1",
    "categoryId":"2",
    "brandId" : "3",
    "productName": "Shoes", 
    "price" : "5600", 
    "thumbnail" : "", 
    "images" : "", 
    "salePrecent" : "5", 
    "quantity" : "", 
    "description" : "this is shoes", 
    "createDate" : "", 
    "updateData" : "", 
    "createdUser" : "",
    "updatedUser" : ""
}

###

GET http://localhost:8080/api/admin




###

DELETE http://localhost:8080/api/admin








