###

POST http://localhost:8080/api/product
Content-Type: application/json

{
    "categoryId":"2",
    "brandId" : "3",
    "productName": "Shoes", 
    "price" : "5600", 
    "salePrecent" : "5", 
    "description" : "this is shoes", 

}

###

GET http://localhost:8080/api/product




###

DELETE http://localhost:8080/api/product







